@startuml

title <b> 회원 - 일반 </b>

actor actor
participant front
participant module_api
participant module_user

== 회원 조회 ==
actor -> front
front -> module_api
note left:조회 조건 (복합 조회 가능)\nemail, nickname
module_api <-> module_user: 회원 조회

== 회원 정보 수정 ==
actor -> front
front -> module_api
note left: nickname
module_api <-> module_user: 회원 정보 수정

== 비밀번호 수정 ==
actor -> front
front -> module_api
note left: newPassword
module_api <-> module_user: 비밀번호 수정

@enduml
