@startuml

title <b> 회원 - 미인증 </b>

actor actor
participant front
participant module_api
participant module_user
participant module_smtp

== 일반 회원 등록 ==
actor -> front
front -> module_api
note left:email, nickname, password
module_api <-> module_user: 회원 조회 - email 존재 여부
module_api -> module_api: uuid 생성 & 입력 받은 정보 인메모리에 저장
module_api -> module_smtp: 등록 redirecUrl을 email로 전송 (+uuid)

actor -> module_api: redirecUrl로 접근
module_api <-> module_user: 일반 회원 등록
note left:email, nickname

== 회원 조회 ==
actor -> front
front -> module_api
note left:조회 조건 (복합 조회 가능)\nemail, nickname
module_api <-> module_user: 회원 조회

== 비밀번호 변경 ==
actor -> front
front -> module_api
note left:email, nickname
module_api <-> module_user: 회원 조회 - email & nickname 일치 확인
module_api -> module_api: uuid 생성 후 인메모리에 저장
module_api -> module_smtp: 비밀번호 초기화 redirecUrl을 email로 전송 (+uuid)

actor -> module_api: redirecUrl로 접근
front <- module_api: 비밀번호 변경 페이지로 redirect
front -> module_api
note left:newPassword, uuid
module_api -> module_api: uuid 검증
module_api <-> module_user: 비밀번호 변경


== 인증 (로그인) ==

@enduml

